export enum ErrorCode {
  // Generic / HTTP errors
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  BAD_GATEWAY = 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',
  HTTP_ERROR = 'HTTP_ERROR',

  // Auth & Token
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_INVALID_FORMAT = 'TOKEN_INVALID_FORMAT',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_BLACKLISTED = 'TOKEN_BLACKLISTED',
  TOKEN_AUDIENCE_MISMATCH = 'TOKEN_AUDIENCE_MISMATCH',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_BLACKLISTED = 'REFRESH_TOKEN_BLACKLISTED',

  // OTP & Verification
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS_EXCEEDED = 'OTP_MAX_ATTEMPTS_EXCEEDED',
  OTP_COOLDOWN_ACTIVE = 'OTP_COOLDOWN_ACTIVE',
  VERIFICATION_TOKEN_INVALID = 'VERIFICATION_TOKEN_INVALID',
  VERIFICATION_TOKEN_EXPIRED = 'VERIFICATION_TOKEN_EXPIRED',

  // Accounts
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_PHONE_ALREADY_EXISTS = 'ACCOUNT_PHONE_ALREADY_EXISTS',
  ACCOUNT_EMAIL_ALREADY_EXISTS = 'ACCOUNT_EMAIL_ALREADY_EXISTS',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // Staff
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_USERNAME_ALREADY_EXISTS = 'STAFF_USERNAME_ALREADY_EXISTS',
  STAFF_CODE_ALREADY_EXISTS = 'STAFF_CODE_ALREADY_EXISTS',
  STAFF_INACTIVE = 'STAFF_INACTIVE',
  STAFF_LOCKED = 'STAFF_LOCKED',
  STAFF_CANNOT_DELETE_SELF = 'STAFF_CANNOT_DELETE_SELF',

  // Facilities
  FACILITY_NOT_FOUND = 'FACILITY_NOT_FOUND',
  FACILITY_CODE_ALREADY_EXISTS = 'FACILITY_CODE_ALREADY_EXISTS',
  FACILITY_PARENT_NOT_FOUND = 'FACILITY_PARENT_NOT_FOUND',
  FACILITY_PARENT_CANNOT_BE_SELF = 'FACILITY_PARENT_CANNOT_BE_SELF',
  FACILITY_ACCESS_DENIED = 'FACILITY_ACCESS_DENIED',
  FACILITY_HAS_CHILDREN = 'FACILITY_HAS_CHILDREN',

  // Patient Links & Health Profiles
  PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND',
  PATIENT_LINK_NOT_FOUND = 'PATIENT_LINK_NOT_FOUND',
  PATIENT_ALREADY_LINKED = 'PATIENT_ALREADY_LINKED',
  PATIENT_NOT_LINKED = 'PATIENT_NOT_LINKED',
  HEALTH_PROFILE_NOT_FOUND = 'HEALTH_PROFILE_NOT_FOUND',
  HEALTH_PROFILE_ACCESS_DENIED = 'HEALTH_PROFILE_ACCESS_DENIED',
  HEALTH_RECORD_NOT_FOUND = 'HEALTH_RECORD_NOT_FOUND',

  // Clinical, Examinations & Prescriptions
  EXAMINATION_NOT_FOUND = 'EXAMINATION_NOT_FOUND',
  EXAMINATION_ALREADY_COMPLETED = 'EXAMINATION_ALREADY_COMPLETED',
  EXAMINATION_ALREADY_CANCELLED = 'EXAMINATION_ALREADY_CANCELLED',
  CHRONIC_DISEASE_NOT_FOUND = 'CHRONIC_DISEASE_NOT_FOUND',
  CHRONIC_DISEASE_CODE_ALREADY_EXISTS = 'CHRONIC_DISEASE_CODE_ALREADY_EXISTS',
  TREATMENT_PLAN_NOT_FOUND = 'TREATMENT_PLAN_NOT_FOUND',
  TREATMENT_TARGET_NOT_FOUND = 'TREATMENT_TARGET_NOT_FOUND',
  TREATMENT_DICTIONARY_NOT_FOUND = 'TREATMENT_DICTIONARY_NOT_FOUND',
  TREATMENT_DICTIONARY_CODE_ALREADY_EXISTS = 'TREATMENT_DICTIONARY_CODE_ALREADY_EXISTS',
  PRESCRIPTION_SCHEDULE_NOT_FOUND = 'PRESCRIPTION_SCHEDULE_NOT_FOUND',
  TIMESLOT_NOT_FOUND = 'TIMESLOT_NOT_FOUND',
  TIMESLOT_ALREADY_EXISTS = 'TIMESLOT_ALREADY_EXISTS',

  // Care Requests & SOS
  CARE_REQUEST_NOT_FOUND = 'CARE_REQUEST_NOT_FOUND',
  CARE_REQUEST_ALREADY_ASSIGNED = 'CARE_REQUEST_ALREADY_ASSIGNED',
  CARE_REQUEST_ALREADY_RESOLVED = 'CARE_REQUEST_ALREADY_RESOLVED',
  CARE_REQUEST_OPEN_EXISTS = 'CARE_REQUEST_OPEN_EXISTS',
  SOS_CASE_ALREADY_ASSIGNED = 'SOS_CASE_ALREADY_ASSIGNED',
  SOS_CASE_ALREADY_RESOLVED = 'SOS_CASE_ALREADY_RESOLVED',
  SOS_CASE_OPEN_EXISTS = 'SOS_CASE_OPEN_EXISTS',

  // Care Packages & Subscriptions
  CARE_PACKAGE_NOT_FOUND = 'CARE_PACKAGE_NOT_FOUND',
  CARE_PACKAGE_CODE_ALREADY_EXISTS = 'CARE_PACKAGE_CODE_ALREADY_EXISTS',
  CARE_PACKAGE_INACTIVE = 'CARE_PACKAGE_INACTIVE',
  CARE_SUBSCRIPTION_NOT_FOUND = 'CARE_SUBSCRIPTION_NOT_FOUND',
  CARE_SUBSCRIPTION_EXPIRED = 'CARE_SUBSCRIPTION_EXPIRED',
  CARE_SUBSCRIPTION_ALREADY_ACTIVE = 'CARE_SUBSCRIPTION_ALREADY_ACTIVE',
  CARE_SUBSCRIPTION_INVALID_STATUS = 'CARE_SUBSCRIPTION_INVALID_STATUS',
  CARE_SUBSCRIPTION_ALREADY_CANCELLED = 'CARE_SUBSCRIPTION_ALREADY_CANCELLED',
  CARE_SUBSCRIPTION_ALREADY_EXPIRED = 'CARE_SUBSCRIPTION_ALREADY_EXPIRED',

  // Conversations
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ACCESS_DENIED = 'CONVERSATION_ACCESS_DENIED',
  CONVERSATION_CLOSED = 'CONVERSATION_CLOSED',
  CONVERSATION_ARCHIVED = 'CONVERSATION_ARCHIVED',
  CONVERSATION_MESSAGE_NOT_FOUND = 'CONVERSATION_MESSAGE_NOT_FOUND',
  CONVERSATION_MESSAGE_CANNOT_DELETE = 'CONVERSATION_MESSAGE_CANNOT_DELETE',

  // Risk Assessments
  RISK_ASSESSMENT_NOT_FOUND = 'RISK_ASSESSMENT_NOT_FOUND',
  RISK_ASSESSMENT_RESULT_NOT_FOUND = 'RISK_ASSESSMENT_RESULT_NOT_FOUND',

  // Storage & Files
  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_INVALID = 'FILE_TYPE_INVALID',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  OCR_FAILED = 'OCR_FAILED',
}
