export enum ErrorCode {
  // Validation errors (400)
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',

  // Authentication errors (401)
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // Authorization errors (403)
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Not found errors (404)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PRESCRIPTION_SCHEDULE_NOT_FOUND = 'PRESCRIPTION_SCHEDULE_NOT_FOUND',
  TIMESLOT_NOT_FOUND = 'TIMESLOT_NOT_FOUND',

  // Conflict errors (409)
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  TIMESLOT_ALREADY_EXISTS = 'TIMESLOT_ALREADY_EXISTS',
  SOS_CASE_ALREADY_ASSIGNED = 'SOS_CASE_ALREADY_ASSIGNED',
  SOS_CASE_ALREADY_RESOLVED = 'SOS_CASE_ALREADY_RESOLVED',
  SOS_CASE_OPEN_EXISTS = 'SOS_CASE_OPEN_EXISTS',
  PATIENT_NOT_LINKED = 'PATIENT_NOT_LINKED',

  // Too many requests (429)
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Server errors (500)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  OCR_FAILED = 'OCR_FAILED',
}
